import React, { createContext, useState, useContext } from 'react';

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState('en');

    // Translation Dictionary
    const translations = {
        en: {
            title: "AI Legal Assistant",
            subtitle: "Online • v1.0",
            introTitle: "How can I help you today?",
            introText: "I am trained on the Indian Penal Code (IPC), Bhartiya Nyaya Sanhita (BNS), and other legal frameworks. Ask me anything.",
            placeholder: "Type a message regarding your legal queries...",
            loading: "Generating response via secure stream...",
            sources: "Sources Referenced:",
            q1: "What is Section 302?",
            q2: "Explain property rights for women",
            q3: "Difference between IPC and BNS",
            homeWelcome: "Is This Legal?",
            homeSubtitle: "Your personal legal expert, powered by advanced AI.",
            startChat: "Start Consultation",
            uploadDocs: "Upload Documents",
            howToUse: "How to Use",
            // Upload Page
            docAnalysis: "Document Analysis",
            uploadDescription: "Upload your legal documents for instant summary and risk assessment using our advanced RAG engine.",
            dropFiles: "Drop your files here",
            browseFiles: "browse files",
            or: "or",
            fromDevice: "from your computer",
            processing: "Processing Document...",
            uploadFailed: "Upload Failed",
            clickRetry: "Click to try again",
            docPreview: "Document Preview",
            aiSummary: "AI Summary",
            generatedBy: "Generated by Advanced RAG",
            disclaimer: "Legal Disclaimer",
            disclaimerText: "This summary is generated by AI and may not be 100% accurate. Please review the full document for critical information.",
            backDashboard: "Back to Dashboard",
            uploadNew: "Upload New File",
            // How To Use Page
            backHome: "Back to Home",
            userGuide: "User Guide",
            translating: "Translating content...",
            // Settings Page
            settingsTitle: "Settings",
            configDesc: "Configure your application endpoints",
            serverUrl: "Server URL",
            serverUrlHelp: "Point this to your backend server instance. Default is",
            saveChanges: "Save Changes",
            reset: "Reset",
            resetTooltip: "Reset to default",
            savedSuccess: "Settings saved successfully!"
        },
        hi: {
            title: "एआई कानूनी सहायक",
            subtitle: "ऑनलाइन • v1.0",
            introTitle: "आज मैं आपकी कैसे मदद कर सकता हूँ?",
            introText: "मैं भारतीय दंड संहिता (IPC), भारतीय न्याय संहिता (BNS), और अन्य कानूनी ढांचों पर प्रशिक्षित हूँ। मुझसे कुछ भी पूछें।",
            placeholder: "अपने कानूनी प्रश्न यहाँ लिखें...",
            loading: "सुरक्षित स्ट्रीम के माध्यम से उत्तर उत्पन्न किया जा रहा है...",
            sources: "संदर्भ:",
            q1: "धारा 302 क्या है?",
            q2: "महिलाओं के संपत्ति अधिकारों को समझाएं",
            q3: "IPC और BNS के बीच अंतर",
            homeWelcome: "क्या यह कानूनी है?",
            homeSubtitle: "आपका व्यक्तिगत कानूनी विशेषज्ञ, उन्नत एआई द्वारा संचालित।",
            startChat: "परामर्श शुरू करें",
            uploadDocs: "दस्तावेज़ अपलोड करें",
            howToUse: "उपयोग कैसे करें",
            // Upload Page
            docAnalysis: "दस्तावेज़ विश्लेषण",
            uploadDescription: "त्वरित सारांश और जोखिम मूल्यांकन के लिए अपने कानूनी दस्तावेज़ अपलोड करें।",
            dropFiles: "अपनी फाइलें यहाँ छोड़ें",
            browseFiles: "फाइलें चुनें",
            or: "या",
            fromDevice: "अपने कंप्यूटर से",
            processing: "दस्तावेज़ संसाधित हो रहा है...",
            uploadFailed: "अपलोड विफल",
            clickRetry: "पुनः प्रयास करें",
            docPreview: "दस्तावेज़ पूर्वावलोकन",
            aiSummary: "एआई सारांश",
            generatedBy: "उन्नत RAG द्वारा निर्मित",
            disclaimer: "कानूनी अस्वीकरण",
            disclaimerText: "यह सारांश एआई द्वारा उत्पन्न है और 100% सटीक नहीं हो सकता है। कृपया महत्वपूर्ण जानकारी के लिए पूरा दस्तावेज़ देखें।",
            backDashboard: "वापस डैशबोर्ड पर",
            uploadNew: "नई फाइल अपलोड करें",
            // How To Use Page
            backHome: "वापस होम पर",
            userGuide: "उपयोगकर्ता गाइड",
            translating: "सामग्री का अनुवाद हो रहा है...",
            // Settings Page
            settingsTitle: "सैटिंग्स",
            configDesc: "अपने एप्लिकेशन एंडपॉइंट कॉन्फ़िगर करें",
            serverUrl: "सर्वर URL",
            serverUrlHelp: "इसे अपने बैकएंड सर्वरInstance की ओर इंगित करें। डिफ़ॉल्ट है",
            saveChanges: "परिवर्तन सहेजें",
            reset: "रीसेट",
            resetTooltip: "डिफ़ॉल्ट पर रीसेट करें",
            savedSuccess: "सैटिंग्स सफलतापूर्वक सहेजी गईं!"
        }
    };

    // Get translations based on language
    // For romanized Hindi, use English UI but send 'hi-romanized' to backend
    const getTranslations = (lang) => {
        if (lang === 'hi-romanized') {
            return translations.en; // Use English UI for romanized
        }
        return translations[lang] || translations.en;
    };

    const t = getTranslations(language);

    const changeLanguage = (newLang) => {
        setLanguage(newLang);
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, changeLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext(LanguageContext);
